"""
Example: Complete workflow - Spider to discover URLs, then extract markdown.

This demonstrates the two-phase approach:
1. Spider discovers all relevant URLs
2. PageExtractor creates markdown for each URL
"""

import asyncio
import logging
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from scraper.page_extractor import (
    WebSpider, 
    SpiderConfig, 
    PageExtractor,
    ExtractionConfig
)


logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)


async def crawl_and_extract_site(
    start_url: str,
    output_file: str = "output_combined.md"
):
    """
    Complete workflow: Crawl site to find URLs, then extract markdown.
    
    Args:
        start_url: URL to start crawling from
        output_file: Where to save combined markdown
    """
    print("\n" + "="*80)
    print("PHASE 1: DISCOVERING URLs")
    print("="*80 + "\n")
    
    # Configure spider
    spider_config = SpiderConfig(
        max_depth=2,
        max_urls=50,
        url_patterns=[
            # Customize these patterns for your target site
            r'.*/lineup.*',
            r'.*/artists.*',
            r'.*/schedule.*',
            r'.*/tickets.*',
            r'.*/info.*',
            r'.*/about.*',
            r'.*/location.*',
        ],
        delay_between_requests=0.5
    )
    
    # Run spider
    async with WebSpider(spider_config) as spider:
        spider_result = await spider.crawl(start_url)
    
    print(f"\n✓ Spider completed:")
    print(f"  - Discovered: {len(spider_result.discovered_urls)} URLs")
    print(f"  - Visited: {len(spider_result.visited_urls)} URLs")
    print(f"  - External contextual: {len(spider_result.external_contextual_urls)} URLs")
    print(f"  - Failed: {len(spider_result.failed_urls)} URLs")
    print(f"  - Time: {spider_result.total_time_seconds:.2f}s")
    
    # Show discovered URLs
    print("\nDiscovered URLs:")
    for i, url in enumerate(sorted(spider_result.discovered_urls), 1):
        if url in spider_result.external_contextual_urls:
            print(f"  {i}. 🎫 {url}")
        else:
            print(f"  {i}. {url}")
    
    if spider_result.external_contextual_urls:
        print("\n📋 External contextual URLs (e.g., ticket sellers):")
        for url in sorted(spider_result.external_contextual_urls):
            print(f"  🎫 {url}")
    
    if not spider_result.discovered_urls:
        print("\n✗ No URLs discovered. Exiting.")
        return
    
    # Ask user if they want to proceed
    print("\n" + "="*80)
    proceed = input(f"\nExtract markdown from {len(spider_result.discovered_urls)} URLs? (y/n): ")
    if proceed.lower() != 'y':
        print("Extraction cancelled.")
        return
    
    print("\n" + "="*80)
    print("PHASE 2: EXTRACTING MARKDOWN")
    print("="*80 + "\n")
    
    # Configure extractor
    extractor_config = ExtractionConfig(
        browser_type="firefox",
        stealth_mode=True,
        extraction_strategy="semantic",
        wait_state="networkidle"
    )
    
    # Extract markdown from all URLs
    successful_extractions = []
    failed_extractions = []
    
    async with PageExtractor(extractor_config) as extractor:
        for i, url in enumerate(sorted(spider_result.discovered_urls), 1):
            print(f"[{i}/{len(spider_result.discovered_urls)}] Extracting: {url}")
            
            try:
                result = await extractor.extract(url)
                successful_extractions.append(result)
                print(f"  ✓ Extracted {result.content_length} chars (quality: {result.content_quality_score:.2f})")
            except Exception as e:
                failed_extractions.append((url, str(e)))
                print(f"  ✗ Failed: {e}")
    
    print(f"\n✓ Extraction completed:")
    print(f"  - Successful: {len(successful_extractions)}")
    print(f"  - Failed: {len(failed_extractions)}")
    
    # Combine all markdown
    print("\n" + "="*80)
    print("PHASE 3: COMBINING RESULTS")
    print("="*80 + "\n")
    
    combined_parts = []
    
    # Add header
    combined_parts.append(f"# Scraped Content from {start_url}\n")
    combined_parts.append(f"Generated by crawl_and_extract\n")
    combined_parts.append(f"Total pages: {len(successful_extractions)}\n")
    combined_parts.append("\n---\n")
    
    # Add each page
    for i, result in enumerate(successful_extractions, 1):
        combined_parts.append(f"\n\n## Page {i}: {result.title or result.url}\n")
        combined_parts.append(f"**URL:** {result.url}\n")
        combined_parts.append(f"**Quality Score:** {result.content_quality_score:.2f}/100\n")
        combined_parts.append(f"\n{result.markdown}\n")
        combined_parts.append("\n---\n")
    
    # Add failed URLs section if any
    if failed_extractions:
        combined_parts.append("\n\n## Failed URLs\n")
        for url, error in failed_extractions:
            combined_parts.append(f"- {url}\n  Error: {error}\n")
    
    combined_markdown = "".join(combined_parts)
    
    # Save to file
    output_path = Path(output_file)
    output_path.write_text(combined_markdown)
    
    print(f"✓ Combined markdown saved to: {output_path.absolute()}")
    print(f"  Total size: {len(combined_markdown)} characters")
    
    # Show summary
    print("\n" + "="*80)
    print("SUMMARY")
    print("="*80)
    print(f"Start URL: {start_url}")
    print(f"URLs discovered: {len(spider_result.discovered_urls)}")
    print(f"  - Internal: {len(spider_result.discovered_urls) - len(spider_result.external_contextual_urls)}")
    print(f"  - External contextual: {len(spider_result.external_contextual_urls)} (e.g., ticket sellers)")
    print(f"Pages extracted: {len(successful_extractions)}")
    print(f"Extraction failures: {len(failed_extractions)}")
    print(f"Output file: {output_path.absolute()}")
    print(f"Total time: {spider_result.total_time_seconds:.2f}s (spider) + extraction time")


async def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: python crawl_and_extract_example.py <URL> [output_file]")
        print("\nExample:")
        print("  python crawl_and_extract_example.py https://example.com")
        print("  python crawl_and_extract_example.py https://example.com output.md")
        sys.exit(1)
    
    start_url = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "output_combined.md"
    
    await crawl_and_extract_site(start_url, output_file)


if __name__ == "__main__":
    asyncio.run(main())
